plugins:
  - jekyll-seo-tag
title: Karthick Shankar
description: Karthick Shankar's portfolio website to consolidate projects and seek internships
url: http://karthickshankar.com
author: Karthick Shankar
